//alert('Sí funciona');
var ruta = window.location;
console.log(ruta);
document.write("Estás aquí:" + ruta.origin);
var ruta2 = navigator.location;
console.log(ruta2);
var ruta3 = document.location;
console.log(ruta3);
var ruta4 = console.location;
console.log(ruta4);